Added Jayo PLA+
Donkie/SpoolmanDB pull request #1
Opened 2024-05-13 08:18 UTC by Disane87

Added PLA+ from Jayo 

https://www.amazon.de/JAYO-Filament-1-75mm-Plus-1-1kg/dp/B0CD25JXQX

2024-05-13 08:53 UTC, Disane87 commented
@Donkie I have created a Script whoch gathers the flaments from the API. Do you mind when I add this to the repo?

2024-05-13 09:28 UTC, Donkie commented
That's an interesting idea, though I think it's better if people in general grab information from the manufacturer website, since then the info will be more complete. Your script only populates a single weight item for example, while the supplier may well sell multiple sizes.

You may use your script but please ensure the info is complete for each filament you add.

2024-05-13 09:40 UTC, Disane87 commented
> That's an interesting idea, though I think it's better if people in general grab information from the manufacturer website, since then the info will be more complete. Your script only populates a single weight item for example, while the supplier may well sell multiple sizes.
Yeah thats one where I'm currently working on. But actually I don't have any other siztes so I haven't done it yet. 

> You may use your script but please ensure the info is complete for each filament you add.
Yeah sure! Since I add the filaments correctly to spoolman by infos of the manufacturer there should be no problem from my side.

The script is also inteded to create a base from your spoolman and than add more details (manually) if needed.
It's just an POC to get more traction into the process of adding filaments.

2024-05-13 17:31 UTC, Donkie requested changes

2024-05-14 12:12 UTC, Disane87 commented on filaments/Jayo.json
> +            "name": "Jayo {color_name}",
Did that and renamed files to lowercase

2024-05-14 13:33 UTC, Donkie requested changes

2024-05-14 13:33 UTC, Donkie commented on filaments/prusament.json
> +    "manufacturer": "prusament",
Uppercase P

2024-05-14 13:33 UTC, Donkie commented on filaments/jayo.json
> +            "name": "Jayo {color_name}",
Still have company name on some of these

2024-05-14 13:33 UTC, Donkie commented on filaments/jayo.json
> +                    "name": "Gras-Green",
Grass Green I presume?

2024-05-14 13:33 UTC, Donkie commented on filaments/jayo.json
> +    "manufacturer": "Jayo",
Should be JAYO right?

2024-05-14 13:33 UTC, Donkie commented on filaments/creality.json
> +                    "name": "Hyper - Grey",
Hyper should be added to the filament name instead

2024-05-14 13:38 UTC, Disane87 commented
Sorry I shouldn't have done these changes with that little review from my side. Totally was my fault! Changed the things you've requested

2024-05-14 14:28 UTC, merged